# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLMmEQUxV60surluwAgR7xaLiJubFkFm

Estrutura de dados

Listas
"""

#Criando uma lista chamada animais
animais = [1,2,3]
animais

animais = ["cachorro", "gato", 12345, 6.5]
animais

#Imprimindo o primeiro elemento da lista
animais[0]

#Imprimindo o 4 elemento da lista
animais[3]

#Substituindo o primeiro elemento da lista
animais[0] = "papagaio"

animais

#Removendo gato da lista
animais.remove("gato")

animais

len(animais)

"gato" in animais

lista