# -*- coding: utf-8 -*-
"""Python pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QfiE9JhueAf8LlFzKv2taMpw0FW7aZib

Python para análise de dados (Pandas)
"""

# Importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/Colab/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

# Visualizadno as 5 primeirads linhas
df.head()

df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap":"PIB"})

df.head(10)

#Total de linhas e colunas
df.shape

df.columns

df.dtypes

#Ultimas linhas
df.tail()

df.describe()

df["Continente"].unique()

Oceania = df.loc[df["Continente"] == "Oceania"]
Oceania.head()

Oceania["Continente"].unique()

df.groupby("Continente")["Pais"].nunique()

df.groupby("Ano")["Expectativa de vida"].mean()

df["PIB"].mean()

df["PIB"].sum()

